# -*- coding: utf-8 -*-

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#Find the sum of all the even-valued terms in the sequence which do not exceed four million.

sum = 2
frst = 1
scnd = 2
while (frst + scnd) < 4000000:
  tmp = frst + scnd
  if tmp%2 == 0:
    sum += tmp
  frst = scnd
  scnd = tmp

print sum
